### ISSUE TITLE
Examples host not working?

### ISSUE THREAD

**Issue by u0xee** [rm-hull/programming-enchiladas#10]
*This is not an issue with the repo as far as I know, and so may not be appropriate as an issue.

The examples all sound awesome! But I see a 500 return code from the host. For example, [8262502](http://programming-enchiladas.destructuring-bind.org/rm-hull/8262502).

**Comment by rm-hull** [comment]
Hi - the (free) mongo database that hosts the site is no longer free (or accessible even), so I took the decision to take the site down temporarily while I assess what the best course of action to take. It should be straightforward to strip out the mongo integration without too much loss of functionality.

**Comment by rm-hull** [comment]
Site is now back up but without mongo

**Comment by u0xee** [comment]
These are so cool! Thank you!
