### ISSUE TITLE
Heroku error

### ISSUE THREAD

**Issue by wiseman** [rm-hull/programming-enchiladas#8]
I might have broken something.  http://programming-enchiladas.destructuring-bind.org/wiseman/5eb4ef4114c73f277931 shows a Heroku error:
```
com.mongodb.MongoServerSelectionException
Unable to connect to any servers
```

Just before that message I had seen a Java heap exception.

**Comment by rm-hull** [comment]
Dont worry - the server it's on is a 512Mb digital ocean droplet & there is not really enough memory for doing big cljs compiles. I'll restart it. Originally, I had it on a free heroku instance which was woefully inadequate.

On the flip side, I havent spent any time recently keeping up to date with the latest cljs compiler internals - there have been a number of speed improvements which would justify using the latest build, but there were some breaking changes IIRC.

**Comment by rm-hull** [comment]
Restarted - I like your party planner .. http://programming-enchiladas.destructuring-bind.org/wiseman/5eb4ef4114c73f277931 should be working ok now

ideal enchilada fodder

**Comment by wiseman** [comment]
Thanks, Richard.

(It was pretty easy to repurpose your boids example into party-planner.)
